version: "3.7"
services:

  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    networks:
      - smart-home-network
    volumes:
      - ./mosquitto/config:/mosquitto/config
