version: "3.3"
services:

  mosquitto:
    image: arm32v6/eclipse-mosquitto
    restart: always
    ports:
      - "0.0.0.0:1883:1883"

  home-assistant:
      container_name: home-assistant
      restart: always
      build:
        context: ./home-assistant
      ports:
        - "0.0.0.0:8123:8123"
        - "0.0.0.0:5678:5678"
      external_links:
        - mosquitto:mqtt
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./home-assistant/config:/config
        - ./letsencrypt:/letsencrypt

  letsencrypt:
      image: linuxserver/swag:arm32v7-version-1.9.0
      restart: always
      container_name: letsencrypt
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=zorcec.duckdns.org
        - VALIDATION=http
        - DUCKDNSTOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
        - EMAIL=zorcec@gmail.com
        - STAGING=false
      volumes:
        - ./letsencrypt:/config
      ports:
        - "0.0.0.0:443:443"
        - "0.0.0.0:80:80"

  duckdns:
    image: linuxserver/duckdns:arm32v7-latest
    restart: always
    container_name: duckdns
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=zorcec.duckdns.org
      - TOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
      - LOG_FILE=false