- platform: generic_thermostat
  name: Kitchen
  unique_id: kitchen-thermostat
  heater: switch.down_kitchen_vent
  target_sensor: sensor.tasmota_si7021_temperature_2
  min_temp: 10
  max_temp: 25
  cold_tolerance: 0.2 # when to switch on
  hot_tolerance: 0    # when to switch off
  precision: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Bathroom
  unique_id: bathroom-thermostat
  heater: switch.top_bathroom_valve
  target_sensor: sensor.bathroom_sensor_si7021_temperature
  min_temp: 10
  max_temp: 25
  cold_tolerance: 0.2 # when to switch on
  hot_tolerance: 0    # when to switch off
  precision: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Master Bedroom
  unique_id: bedroom-thermostat
  heater: switch.top_bedroom_valve
  target_sensor: sensor.tasmota_si7021_temperature_3
  min_temp: 10
  max_temp: 25
  cold_tolerance: 0.2 # when to switch on
  hot_tolerance: 0    # when to switch off
  precision: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Top
  unique_id: top-thermostat
  heater: switch.top_livingroom_valve
  target_sensor: sensor.top_sensor_bme280_temperature
  min_temp: 10
  max_temp: 25
  cold_tolerance: 0.2 # when to switch on
  hot_tolerance: 0    # when to switch off
  precision: 0.1
  min_cycle_duration:
    minutes: 1

- platform: generic_thermostat
  name: Bathroom Fan
  unique_id: bathroom-fan
  heater: switch.bathroom_fan
  target_sensor: sensor.bathroom_sensor_si7021_humidity
  ac_mode: True
  min_temp: 50
  max_temp: 100
  cold_tolerance: 3
  hot_tolerance: 0
  precision: 1
  min_cycle_duration:
    minutes: 15