- id: '1673812981370'
  alias: Sets sleep retain status
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "radioSilence" }'
      retain: true
  mode: single
- id: '1676149800565'
  alias: Bathroom fan only when lights are off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: climate.bathroom_fan
      - type: turn_off
        device_id: abda588fde39a2ea6fdd0ae3687aecfd
        entity_id: switch.bathroom_fan
        domain: switch
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'off'
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.bathroom_fan
  mode: single
- id: '1677363623906'
  alias: Correct top dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.top_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.top_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 5f7953a4dcd36d3b3815c06c8bb50127
      entity_id: light.top_main_light
      domain: light
  mode: single
- id: '1677363742332'
  alias: Correct bathroom dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.bathroom_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 57edd179adcda8b16f654d9ff5360e1b
      entity_id: light.bathroom_main_light
      domain: light
  mode: single
- id: '1677364084822'
  alias: Correct kitchen main dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_2
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_2
      state: 'on'
    then:
    - type: turn_off
      device_id: 25d3ef8988dc0179e7b6fa79f87efc3e
      entity_id: light.tasmota_2
      domain: light
  mode: single
- id: '1677364163504'
  alias: Correct kitchen table dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_3
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_3
      state: 'on'
    then:
    - type: turn_off
      device_id: 24e2f44a884006a8f9d8f10b8fb2ca91
      entity_id: light.tasmota_3
      domain: light
  mode: single
- id: '1704456499215'
  alias: Hallway heating
  description: ''
  triggers:
  - hours: /2
    trigger: time_pattern
  conditions: []
  actions:
  - if:
    - condition: time
      after: 05:00:00
      before: '18:00:00'
    then:
    - data: {}
      target:
        entity_id:
        - switch.top_wc_valve
        - switch.down_hallway_vent
      action: switch.turn_on
  - delay:
      hours: 0
      minutes: 8
      seconds: 0
      milliseconds: 0
  - data: {}
    target:
      entity_id:
      - switch.down_hallway_vent
      - switch.top_wc_valve
    action: switch.turn_off
  mode: single
- id: '1733597752568'
  alias: Open window notification (bathroom)
  description: ''
  triggers:
  - type: opened
    device_id: 3650456fef0d585ceff3c398192d4691
    entity_id: 52f89f17e1e4170b3d9bc3b6c208fcbc
    domain: binary_sensor
    trigger: device
  conditions:
  - type: is_open
    condition: device
    device_id: 3650456fef0d585ceff3c398192d4691
    entity_id: 52f89f17e1e4170b3d9bc3b6c208fcbc
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  actions:
  - data:
      message: Prozor u kupaonici je otvoren
      title: Upozorenje
    action: notify.notify
  mode: single
- id: '1733597920601'
  alias: Open window notification (kid)
  description: ''
  triggers:
  - type: opened
    device_id: 6466a2424bfb63a6705e90276c5cfee2
    entity_id: 88d247f1e8c8cf9f8fb3b64433f2ee04
    domain: binary_sensor
    trigger: device
  conditions:
  - type: is_open
    condition: device
    device_id: 6466a2424bfb63a6705e90276c5cfee2
    entity_id: 88d247f1e8c8cf9f8fb3b64433f2ee04
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  actions:
  - data:
      message: Prozor v dječjoj je otvoren
      title: 'Upozorenje '
    action: notify.notify
  mode: single
- id: '1733597939534'
  alias: Open window notification (master bedroom)
  description: ''
  triggers:
  - type: opened
    device_id: ffe02fdd65caaeae4dca8e5f2fa95d36
    entity_id: 9ea36114346056d5116cf06d40baa69e
    domain: binary_sensor
    trigger: device
  conditions:
  - type: is_open
    condition: device
    device_id: ffe02fdd65caaeae4dca8e5f2fa95d36
    entity_id: 9ea36114346056d5116cf06d40baa69e
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  actions:
  - data:
      message: Prozor u spavacoj je otvoren
      title: 'Upozorenje '
    action: notify.notify
  mode: single
- id: '1733606138125'
  alias: Set washmachine to active
  description: ''
  triggers:
  - type: power
    device_id: 9b4b92c42c7aa57ea6ef528470036bb1
    entity_id: 80404132ebaae930f2527be2e0af71ac
    domain: sensor
    trigger: device
    above: 3
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - target:
      entity_id: input_select.washmachine_status
    data:
      options: active
    action: input_select.set_options
  mode: single
- id: '1733606523695'
  alias: Set washmachine to idle
  description: ''
  triggers:
  - type: power
    device_id: 9b4b92c42c7aa57ea6ef528470036bb1
    entity_id: 80404132ebaae930f2527be2e0af71ac
    domain: sensor
    trigger: device
    below: 3
    for:
      hours: 0
      minutes: 3
      seconds: 0
  conditions: []
  actions:
  - target:
      entity_id: input_select.washmachine_status
    data:
      options: idle
    action: input_select.set_options
  mode: single
- id: '1733664384108'
  alias: Waschmaschine notification
  description: ''
  triggers:
  - entity_id:
    - input_select.washmachine_status
    from: active
    to: idle
    for:
      hours: 0
      minutes: 0
      seconds: 0
    trigger: state
  conditions: []
  actions:
  - metadata: {}
    data:
      message: Vešmašina je gotova!
      title: 'Vešmašina '
    action: notify.notify
  mode: single
- id: '1733664738196'
  alias: Windows status
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 3650456fef0d585ceff3c398192d4691
    entity_id: 493ea6de4a7673c5cdda23719accf51d
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 6466a2424bfb63a6705e90276c5cfee2
    entity_id: 987f2fad356ea3a3b77343c20693cecf
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: ffe02fdd65caaeae4dca8e5f2fa95d36
    entity_id: 858f45462aba889ba3451ad8c31c02e6
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      title: Prozori
      message: ''
      Djecja:
        '[object Object]':
  mode: single
- id: '1735160021975'
  alias: Low temp. warning
  description: ''
  trigger:
  - type: temperature
    platform: device
    device_id: d6ad46ed8d528aec3e4c4bbe81bbfe4b
    entity_id: 3d04cd4c3c1d9786d0f561bdec1000ac
    domain: sensor
    below: 10
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: Temperatura je ispod 10°C
  - service: input_number.set_value
    target:
      entity_id: input_number.heat_phaze
    data:
      value: 5
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: input_number.set_value
    target:
      entity_id: input_number.heat_phaze
    data:
      value: 0
  mode: single
- id: '1737203979676'
  alias: Set dryer to idle
  description: ''
  triggers:
  - type: power
    device_id: d7eb729eb34fec046f84f53431e50c7a
    entity_id: 11453766c044dbef8728214568b456aa
    domain: sensor
    trigger: device
    for:
      hours: 0
      minutes: 3
      seconds: 0
    below: 3
  conditions: []
  actions:
  - data:
      options: idle
    action: input_select.set_options
    target:
      entity_id: input_select.dryer_status
  mode: single
- id: '1737204017917'
  alias: Set dryer active
  description: ''
  triggers:
  - type: power
    device_id: d7eb729eb34fec046f84f53431e50c7a
    entity_id: 11453766c044dbef8728214568b456aa
    domain: sensor
    trigger: device
    above: 3
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - data:
      options: active
    action: input_select.set_options
    target:
      entity_id: input_select.dryer_status
  mode: single
