- id: '1673812308634'
  alias: Disables PIR
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOff
  mode: single
- id: '1673812956297'
  alias: Activates PIR
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOn
  mode: single
- id: '1673812981370'
  alias: Sets sleep retain status
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "radioSilence" }'
      retain: true
  mode: single
- id: '1676149800565'
  alias: Bathroom fan only when lights are off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: climate.bathroom_fan
      - type: turn_off
        device_id: abda588fde39a2ea6fdd0ae3687aecfd
        entity_id: switch.bathroom_fan
        domain: switch
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'off'
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.bathroom_fan
  mode: single
- id: '1677363623906'
  alias: Correct top dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.top_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.top_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 5f7953a4dcd36d3b3815c06c8bb50127
      entity_id: light.top_main_light
      domain: light
  mode: single
- id: '1677363742332'
  alias: Correct bathroom dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.bathroom_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 57edd179adcda8b16f654d9ff5360e1b
      entity_id: light.bathroom_main_light
      domain: light
  mode: single
- id: '1677364084822'
  alias: Correct kitchen main dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_2
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_2
      state: 'on'
    then:
    - type: turn_off
      device_id: 25d3ef8988dc0179e7b6fa79f87efc3e
      entity_id: light.tasmota_2
      domain: light
  mode: single
- id: '1677364163504'
  alias: Correct kitchen table dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_3
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_3
      state: 'on'
    then:
    - type: turn_off
      device_id: 24e2f44a884006a8f9d8f10b8fb2ca91
      entity_id: light.tasmota_3
      domain: light
  mode: single
- id: '1687802197772'
  alias: Watering Down
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: 03:00:00
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.downwateringvent
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.downwateringvent
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: switch.downwateringvent
      state: 'off'
    then: []
    else:
    - service: notify.simplepush
      data:
        message: Can't turn off watering vent "down"!
  mode: single
- id: '1688744623083'
  alias: Watering Up
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '23:00:00'
    enabled: true
  - platform: time
    at: 06:30:00
    enabled: true
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.top_watering_vent
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.top_watering_vent
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
    - condition: state
      entity_id: switch.top_watering_vent
      state: 'off'
    then: []
    else:
    - service: notify.simplepush
      data:
        message: Can't turn off watering vent "up"!
  mode: single
- id: '1704456499215'
  alias: Hallway heating
  description: ''
  trigger:
  - platform: time_pattern
    hours: /2
  condition: []
  action:
  - if:
    - condition: time
      after: 05:00:00
      before: '18:00:00'
    then:
    - service: switch.turn_on
      data: {}
      target:
        entity_id:
        - switch.top_wc_valve
        - switch.down_hallway_vent
  - delay:
      hours: 0
      minutes: 4
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.down_hallway_vent
      - switch.top_wc_valve
  mode: single
- id: '1733597752568'
  alias: Open window notification (bathroom)
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 3650456fef0d585ceff3c398192d4691
    entity_id: 493ea6de4a7673c5cdda23719accf51d
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Prozor u kupaonici je otvoren
      title: Upozorenje
  mode: single
- id: '1733597920601'
  alias: Open window notification (kid)
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 6466a2424bfb63a6705e90276c5cfee2
    entity_id: 987f2fad356ea3a3b77343c20693cecf
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Prozor u kupaonici je otvoren
      title: Prozor u kupaonici
  - service: notify.notify
    metadata: {}
    data:
      message: Prozor u dječji sobi je otvoren
      title: Upozorenje
  mode: single
- id: '1733597939534'
  alias: Open window notification (master bedroom)
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: ffe02fdd65caaeae4dca8e5f2fa95d36
    entity_id: 858f45462aba889ba3451ad8c31c02e6
    domain: binary_sensor
    for:
      hours: 0
      minutes: 15
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Prozor u spavacoj je otvoren
      title: Prozor u kupaonici
  - service: notify.notify
    metadata: {}
    data:
      message: Prozor u dječji sobi je otvoren
      title: Upozorenje
  mode: single
