- id: '1673812308634'
  alias: Disables PIR
  description: ''
  trigger:
  - platform: time
    at: '20:30:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOff
  mode: single
- id: '1673812956297'
  alias: Activates PIR
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOn
  mode: single
- id: '1673812981370'
  alias: Sets sleep retain status
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '23:00:00'
  - platform: time
    at: 03:10:00
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "pirOff", "event": "radioSilence" }'
      retain: true
  mode: single
- id: '1676149800565'
  alias: Bathroom fan only when lights are off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: climate.bathroom_fan
      - type: turn_off
        device_id: abda588fde39a2ea6fdd0ae3687aecfd
        entity_id: switch.bathroom_fan
        domain: switch
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'off'
      sequence:
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.bathroom_fan
  mode: single
