- id: '1673812308634'
  alias: Disables PIR
  description: ''
  trigger:
  - platform: time
    at: '21:20:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOff
  mode: single
- id: '1673812956297'
  alias: Activates PIR
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/event
      payload: pirOn
  mode: single
- id: '1673812981370'
  alias: Sets sleep retain status
  description: ''
  trigger:
  - platform: time
    at: '21:00:00'
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "pirOff", "event": "radioSilence" }'
      retain: true
  mode: single
- id: '1676149800565'
  alias: Bathroom fan only when lights are off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      sequence:
      - service: climate.turn_off
        data: {}
        target:
          entity_id: climate.bathroom_fan
      - type: turn_off
        device_id: abda588fde39a2ea6fdd0ae3687aecfd
        entity_id: switch.bathroom_fan
        domain: switch
    - conditions:
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'off'
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
      - service: climate.turn_on
        data: {}
        target:
          entity_id: climate.bathroom_fan
  mode: single
- id: '1677363623906'
  alias: Correct top dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.top_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.top_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 5f7953a4dcd36d3b3815c06c8bb50127
      entity_id: light.top_main_light
      domain: light
  mode: single
- id: '1677363742332'
  alias: Correct bathroom dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_main_light
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.bathroom_main_light
      state: 'on'
    then:
    - type: turn_off
      device_id: 57edd179adcda8b16f654d9ff5360e1b
      entity_id: light.bathroom_main_light
      domain: light
  mode: single
- id: '1677364084822'
  alias: Correct kitchen main dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_2
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_2
      state: 'on'
    then:
    - type: turn_off
      device_id: 25d3ef8988dc0179e7b6fa79f87efc3e
      entity_id: light.tasmota_2
      domain: light
  mode: single
- id: '1677364163504'
  alias: Correct kitchen table dimmer
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.tasmota_3
    to: 'off'
    from: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 2
      milliseconds: 0
  - if:
    - condition: state
      entity_id: light.tasmota_3
      state: 'on'
    then:
    - type: turn_off
      device_id: 24e2f44a884006a8f9d8f10b8fb2ca91
      entity_id: light.tasmota_3
      domain: light
  mode: single
