homeassistant: !include customize/homeassistant.yaml

mqtt: !include customize/mqtt.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: http://zorcec.duckdns.org:8123
  #base_url: https://zorcec.duckdns.org:8123
  #ssl_certificate: /letsencrypt/keys/letsencrypt/cert.pem
  #ssl_key: /letsencrypt/keys/letsencrypt/privkey.pem

# Enables support for tracking state changes over time
history:

recorder:
  purge_keep_days: 30
  commit_interval: 10
  db_url: mysql://root:admin@mariadb/ha?charset=utf8mb4

mobile_app:

logger:
  default: error
  logs:
    custom_components: debug

group: !include customize/groups.yaml
script: !include customize/scripts.yaml
automation: !include customize/automation.yaml
intent_script: !include customize/intent-scripts.yaml

#light: !include_dir_merge_list customize/lights/
#switch: !include_dir_merge_list customize/switches/
#sensor: !include_dir_merge_list customize/sensors/
#climate: !include_dir_merge_list customize/climate/
