homeassistant: !include customize/homeassistant.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: https://zorcec.duckdns.org:8123
  ssl_certificate: /letsencrypt/keys/letsencrypt/cert.pem
  ssl_key: /letsencrypt/keys/letsencrypt/privkey.pem

# Enables support for tracking state changes over time
history:

recorder:
  auto_purge: True
  auto_repack: True
  purge_keep_days: 30
  commit_interval: 10
  db_url: mysql://root:admin@mariadb/ha
  exclude:
    entities:
      - heating_control.until_next_phaze
      - heating_control.next_phaze
      - heating_control.next_phaze_formatted

mobile_app:

energy:

powercalc:

backup:

logger:
  default: info
  logs:
    custom_components: debug
    python_script: debug

group:

python_script:

heating_control:

input_number:
  heat_phaze:
    name: Heating Cycle
    min: 0
    max: 60
    step: 5
    unit_of_measurement: "min"
    icon: mdi:clock-outline
  wait_phaze:
    name: Waiting Cycle
    min: 0
    max: 60
    step: 5
    unit_of_measurement: "min"
    icon: mdi:clock-outline
  target_output:
    name: Target Temp.
    min: 25
    max: 40
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:temperature

input_select:
  heating_type:
    name: Type
    options:
      - Target
      - Rotation
      - Continuous
    initial: Target
    icon: mdi:format-list-bulleted-type

# mqtt:
#   binary_sensor:
#     - name: Top Hallway Motion Sensor
#       state_topic: stat/tasmota_C7CB0D/PIR
#       device_class: motion
#       force_update: true
#       availability_topic: tele/tasmota_C7CB0D/LWT
#       payload_on: "1"
#       payload_off: "0"
#       payload_available: Online
#       payload_not_available: Offline
#       unique_id: 'tasmota_C7CB0D_motion'

#     - name: Down Hallway Motion Sensor
#       state_topic: stat/tasmota_F985BB/PIR
#       device_class: motion
#       force_update: true
#       availability_topic: tele/tasmota_F985BB/LWT
#       payload_on: "1"
#       payload_off: "0"
#       payload_available: Online
#       payload_not_available: Offline
#       unique_id: 'tasmota_F985BB_motion'

#     - name: Middle Hallway Motion Sensor
#       state_topic: stat/tasmota_FA4CF2/PIR
#       device_class: motion
#       force_update: true
#       availability_topic: tele/tasmota_FA4CF2/LWT
#       payload_on: "1"
#       payload_off: "0"
#       payload_available: Online
#       payload_not_available: Offline
#       unique_id: 'tasmota_FA4CF2_motion'

sensor: !include_dir_merge_list customize/sensors/
binary_sensor: !include_dir_merge_list customize/binary_sensors/
switch: !include_dir_merge_list customize/switches/
climate: !include_dir_merge_list customize/climate/
automation: !include automations.yaml