- id: reboot_ha
  initial_state: true
  alias: 'Reboot HA daily'
  trigger:
  - platform: time
    at: '03:00:00'
  action:
  - service: homeassistant.restart

- id: set-sleep-light-mode
  alias: 'Activates sleep lights mode'
  trigger:
  - platform: time
    at: '20:00:00'
  - platform: time
    at: '23:00:00'
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "pirOff", "event": "radioSilence" }'
      retain: true

- id: set-evening-light-mode
  alias: 'Activates evening lights mode'
  trigger:
  - platform: time
    at: '17:00:00'
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/json
      payload: '{ "event": "pirOn" }'
      retain: true

- id: set-sleep-climate
  alias: 'Set sleep climate mode'
  trigger:
  - platform: time
    at: '20:00:00'
  action:
  - service: climate.set_preset_mode
    target:
        entity_id: all
    data:
      preset_mode: "sleep"

- id: set-awake-climate
  alias: 'Set awake climate mode'
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: climate.set_preset_mode
    target:
        entity_id: all
    data:
      preset_mode: "home"
