  # Name of the location where Home Assistant is running
  name: House
  # Location required to calculate the time the sun rises and sets
  latitude: 48.277764
  longitude: 14.3073539
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 400
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Customization file
  customize: !include customize.yaml