- platform: tasmota
  internal_id: bathroom/sensor
  name: Bathroom Sensors
  type: sensors
  mac_address: CC:50:E3:08:20:68
  auto_configure: False
  customize:
    WiFiPower: 17
  sensors:
    - type: temperature
    - type: pressure
    - type: humidity
      offset: 1.2

- platform: tasmota
  internal_id: bathroom/water_sensor
  name: Bathroom Water Sensors
  type: sensors
  mac_address: 80:7D:3A:B7:AB:70
  auto_configure: False
  sensors:
    - type: temperature
