- platform: tasmota
  internal_id: undefined/touch
  name: Undefined touch light
  type: touch
  multipress:

- platform: tasmota
  internal_id: undefined/switch
  name: Undefined switch as light
  type: switch

- platform: tasmota
  internal_id: undefined/led
  name: Undefined LED controller
  type: led_controller_rgbw
