- platform: tasmota
  internal_id: top/led1
  name: TEST top/led1
  type: led_controller
  motion_mode: turn_on
  motion_iterval: 300
  motion_trackers:
    - room

- platform: tasmota
  internal_id: top/touch2
  name: TEST top/touch2
  type: touch

- platform: tasmota
  internal_id: top/switch1
  name: Test top/switch1 (as light)
  type: switch