- platform: tasmota
  internal_id: down/dimmer1
  name: Down Main
  type: dimmer
  mac_address: 84:F3:EB:F9:A3:87
  customize:
    WiFiPower: 16
    PwmFrequency: 3200
    DimmerRange: 30,100
  auto_configure: False

- platform: tasmota
  internal_id: down/touch1
  name: Down Kitchen
  type: touch
  _motion_mode: None
  _motion_iterval: 5
  _motion_event_topic: stat/down/touch1/POWER2
  mac_address: C4:4F:33:9E:B8:CB
  customize:
    WiFiPower: 16
  auto_configure: False

- platform: tasmota
  internal_id: down/switch1
  name: Downstairs Stairway
  type: switch
  mac_address: DC:4F:22:F9:85:BB
  customize:
    WiFiPower: 16
  auto_configure: False

- platform: tasmota
  internal_id: down/led_sofa
  name: Down LED Sofa
  type: led_controller_rgb
  mac_address: DC:4F:22:F6:8C:2C
  auto_configure: False
  cutomize:
    topic: down/led_kitchen
    WiFiPower: 16

- platform: tasmota
  internal_id: down/led_kitchen
  name: Down LED Kitchen
  type: led_controller_rgb
  mac_address: DC:4F:22:F5:14:D9
  auto_configure: False
  WiFiPower: 16
