- platform: tasmota
  internal_id: top/touch1
  name: Top Terasse
  type: touch

- platform: tasmota
  internal_id: top/touch2
  name: Top Stairway
  type: touch
  motion_mode: turn_off
  motion_iterval: 30
  motion_trackers:
    - room

- platform: tasmota
  internal_id: top/dimmer1
  name: Top Main
  type: dimmer
  motion_mode: turn_on
  motion_iterval: 300
  motion_trackers:
    - room

- platform: tasmota
  internal_id: top/dimmer2
  name: Top Workplace
  type: dimmer
  motion_mode: turn_on
  motion_iterval: 300
  motion_trackers:
    - room
