- platform: tasmota
  internal_id: top/touch1
  name: Top Terasse
  type: touch

- platform: tasmota
  internal_id: top/touch2
  name: Top Stairway
  type: touch

- platform: tasmota
  internal_id: top/dimmer1
  name: Top Main
  type: dimmer
  multipress:

- platform: tasmota
  internal_id: top/dimmer2
  name: Top Workplace
  type: dimmer

- platform: tasmota
  internal_id: top/workplace_led
  name: Top Workplace LED
  type: led_controller_rgb
