services:

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    restart: unless-stopped
    ports:
      - "0.0.0.0:1883:1883"
  
  home-assistant:
    container_name: home-assistant
    restart: unless-stopped
    build:
      context: ./home-assistant
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:5678:5678"
    external_links:
      - mosquitto:mqtt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home-assistant/config:/config
      - ./letsencrypt:/letsencrypt
    links:
      - "mariadb:mariadb"

  tasmota-webserver:
    image: nginx
    restart: unless-stopped
    container_name: tasmota-webserver
    volumes:
      - ./tasmota-webserver:/usr/share/nginx/html
    ports:
      - "0.0.0.0:8888:80"

  letsencrypt:
   image: linuxserver/swag
   restart: unless-stopped
   container_name: letsencrypt
   cap_add:
     - NET_ADMIN
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/London
     - URL=zorcec.duckdns.org
     - VALIDATION=http
     - DUCKDNSTOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
     - EMAIL=zorcec@gmail.com
     - STAGING=false
   volumes:
     - ./letsencrypt:/config
   ports:
     - "0.0.0.0:443:443"
     - "0.0.0.0:80:80"

  duckdns:
   image: linuxserver/duckdns
   restart: unless-stopped
   container_name: duckdns
   environment:
     - TZ=Europe/London
     - SUBDOMAINS=zorcec.duckdns.org
     - TOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
     - LOG_FILE=false

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mariadb/data:/var/lib/mysql

  ntp:
    image: cturra/ntp
    restart: unless-stopped
    ports:
      - "0.0.0.0:123:123/udp"
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 0.0.0.0:1111:8080
    links:
      - "mariadb:mariadb"
      
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
     - 0.0.0.0:9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./portainer/data:/data

  tasmo-backup:
    restart: unless-stopped
    ports:
        - 0.0.0.0:8259:80
    volumes:
        - ./tasmo-backup/data:/var/www/html/data
    environment:
        - DBTYPE=sqlite
        - DBNAME=data/tasmobackup
    container_name: tasmo-backup
    image: 'danmed/tasmobackupv1'

  hyperion-pc:
    restart: unless-stopped
    image: sirfragalot/hyperion.ng:2.0.15
    volumes:
      - ./hyperion:/root/.hyperion:rw
    ports:
      - 0.0.0.0:19400:19400
      - 0.0.0.0:19445:19445
      - 0.0.0.0:19444:19444
      - 0.0.0.0:8090:8090

  hyperion-tv:
    restart: unless-stopped
    image: sirfragalot/hyperion.ng:2.0.15
    volumes:
      - ./hyperion-tv:/root/.hyperion:rw
    ports:
      - 0.0.0.0:19446:19445
      - 0.0.0.0:19401:19400
      - 0.0.0.0:8091:8090

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_361540efd21bef118f389ed94909ffd0-if00-port0:/dev/ttyUSB0
    ports:
      - 0.0.0.0:9090:8080
    external_links:
      - mosquitto:mqtt
