version: "3.7"
services:
  
  home-assistant:
    container_name: home-assistant
    build:
      context: ./home-assistant
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:5678:5678"
    external_links:
      - mosquitto:mqtt
    networks:
      - smart-home-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home-assistant/config:/config
      - ./letsencrypt:/letsencrypt

  #appdeamon:
  #  container_name: appdeamon
  #  build:
  #    context: ./appdeamon
  #  ports:
  #    - "0.0.0.0:5050:5050"
  #  external_links:
  #    - mosquitto:mqtt
  #    - home-assistant:home-assistant
  #  networks:
  #    - smart-home-network
  #  volumes:
  #    - ./appdeamon/apps:/src/apps

  mosquitto:
    container_name: mosquitto
    build:
      context: ./mosquitto
    ports:
      - "0.0.0.0:1883:1883"
    networks:
      - smart-home-network
    volumes:
      - ./mosquitto/config:/mosquitto/config

  find3:
    image: schollz/find3
    container_name: find3
    networks:
      - smart-home-network
    external_links:
      - mosquitto:mqtt
    volumes:
      - ./find3/data:/data
    ports:
      - "0.0.0.0:8003:8003"
    environment:
      - MQTT_EXTERNAL=mqtt

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    networks:
      - smart-home-network
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=zorcec.duckdns.org
      - TOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
      - LOG_FILE=false

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    networks:
      - smart-home-network
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=zorcec.duckdns.org
      - VALIDATION=http
      - DUCKDNSTOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
      - EMAIL=zorcec@gmail.com
      - STAGING=false
    volumes:
      - ./letsencrypt:/config
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"

#  proxy-manager:
#    container_name: proxy-manager
#    image: jlesage/nginx-proxy-manager
#    ports:
#      - "0.0.0.0:8181:8181"
#      - "0.0.0.0:8080:8080"
#      - "0.0.0.0:4443:4443"
#    volumes:
#      - "/proxy-manager/config:/config:rw"

networks:
  smart-home-network:
    external: true