version: "3.7"
services:
  
  home-assistant:
    container_name: home-assistant
    build:
      context: ./home-assistant
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:5678:5678"
    external_links:
      - mosquitto:mqtt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home-assistant/config:/config
      - ./letsencrypt:/letsencrypt

  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=zorcec.duckdns.org
      - VALIDATION=http
      - DUCKDNSTOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
      - EMAIL=zorcec@gmail.com
      - STAGING=false
    volumes:
      - ./letsencrypt:/config
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"

  tasmota-webserver:
    image: nginx
    container_name: tasmota-webserver
    volumes:
      - ./tasmota-webserver:/usr/share/nginx/html
    ports:
      - "0.0.0.0:8888:80"

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=zorcec.duckdns.org
      - TOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
      - LOG_FILE=false

  mosquitto:
      image: arm32v6/eclipse-mosquitto
      restart: always
      ports:
        - "0.0.0.0:1883:1883"