version: "2.4"
services:

  mosquitto:
    image: eclipse-mosquitto:1.6.14
    restart: always
    ports:
      - "0.0.0.0:1883:1883"
  
  home-assistant:
    container_name: home-assistant
    restart: always
    build:
      context: ./home-assistant
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:5678:5678"
    external_links:
      - mosquitto:mqtt
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./home-assistant/config:/config
      - ./letsencrypt:/letsencrypt
    links:
      - "mariadb:mariadb"

  tasmota-webserver:
    image: nginx
    restart: always
    container_name: tasmota-webserver
    volumes:
      - ./tasmota-webserver:/usr/share/nginx/html
    ports:
      - "0.0.0.0:8888:80"

  letsencrypt:
   image: linuxserver/swag
   restart: always
   container_name: letsencrypt
   cap_add:
     - NET_ADMIN
   environment:
     - PUID=1000
     - PGID=1000
     - TZ=Europe/London
     - URL=zorcec.duckdns.org
     - VALIDATION=http
     - DUCKDNSTOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
     - EMAIL=zorcec@gmail.com
     - STAGING=false
   volumes:
     - ./letsencrypt:/config
   ports:
     - "0.0.0.0:443:443"
     - "0.0.0.0:80:80"

  duckdns:
   image: linuxserver/duckdns
   restart: always
   container_name: duckdns
   environment:
     - TZ=Europe/London
     - SUBDOMAINS=zorcec.duckdns.org
     - TOKEN=ff8777ce-260b-47fc-8939-8d08493546cd
     - LOG_FILE=false

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mariadb/data:/var/lib/mysql

  ntp:
    image: cturra/ntp
    restart: always
    ports:
      - "0.0.0.0:123:123/udp"
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 0.0.0.0:1111:8080
    links:
      - "mariadb:mariadb"
      
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 0.0.0.0:9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./portainer/data:/data

#  dnsmasq:
#    build:
#      context: dnsmasq
#    restart: always
#    ports:
#      - 0.0.0.0:53:53/udp
#      - 0.0.0.0:5380:8080
#    cap_add:
#      - NET_ADMIN
#    network_mode: host
#    volumes:
#      - ./dnsmasq/etc/config:/etc/config

  tasmo-backup:
    ports:
        - 0.0.0.0:8259:80
    volumes:
        - ./tasmo-backup/data:/var/www/html/data
    environment:
        - DBTYPE=sqlite
        - DBNAME=data/tasmobackup
    container_name: tasmo-backup
    image: 'danmed/tasmobackupv1'

  hyperion:
      image: sirfragalot/hyperion.ng:2.0.15
      volumes:
        - /hyperion:/root/.hyperion:rw
      ports:
        - 0.0.0.0:19400:19400
        - 0.0.0.0:19445:19445
        - 0.0.0.0:19444:19444
        - 0.0.0.0:8090:8090
